[FEATURE] Adding Final Boss and Final Boss Stage
DiegoForgan/7599-TrabajoProfesional pull request #22
Opened 2023-02-06 04:09 UTC by DiegoForgan

2023-02-09 04:53 UTC, DiegoForgan commented
Honestly I think the POO Gods will ban me for life of the Object Oriented Heaven.
I feel dirty but the end result works.
Hope it works for you and please be merciful with your criticism. 
Now I'm gonna take a shower to clean myself

2023-02-09 11:32 UTC, juanmg0511 requested changes
No se que paso pero me estalló Unity porque esto estaba 2 veces:

    private void rechargePlayerManaAndHealth()
    {
        playerComponent.AddHealth(playerComponent.GetMaxHealth());
        playerComponent.AddMana(playerComponent.GetMaxMana());
    }

Borré una y empezó a andar. A Nilbud lo maté en menos de 2 minutos con hammer throws, no habré gastado ni un 10% de maná, y cuando murió no se terminó el juego. Lo fui a atacar porque no se acercaba y saca con la espada menos que uno de esos verdes grandes.

Lo jugé en nivel 2. Quedó así al final?

2023-02-09 15:37 UTC, DiegoForgan commented
Salvo las stats creo que esta fixeado!

2023-02-10 12:14 UTC, juanmg0511 requested changes
Si Nilbud tira hechizo para arriba se pegua a el mismo! En las otras 3 direcciones no pasa eso, sale el hechizo normalmente.

El resto de los arreglos 10 puntos!

2023-02-11 17:34 UTC, merged